### ISSUE TITLE
NoSlow, False Positive

### ISSUE THREAD

**Issue by KrUtOy228omg** [thedarthonian/KarmaAC#171]
**Minecraft Version & Client**
1.8.9 LiquidBounce

**Check [What check should trigger if bypass] [What check is triggered if bug]*
NoSlow D

**To Reproduce**
1. Jump
2. Hold sword block

**Was the server lagging? - Was your ping high? - Were there any other factors different from normal gameplay?**
No no, i was just jumping and blocking with sword

**Video of the event**
https://youtu.be/fX-qoBe5mDI

**Comment by thedarthonian** [comment]
Bug was a result of every single added violation being displayed. Even though it decayed instantly ensuring the count never got past 1 (the green notif comes in at 20) it appeared as a major issue.
