### ISSUE TITLE
FastLadder bypass

### ISSUE THREAD

**Issue by KrUtOy228omg** [thedarthonian/KarmaAC#172]
**Minecraft Version & Client**
1.8.9 LiquidBounce FastLadder mode AAC

**Check [What check should trigger if bypass] [What check is triggered if bug]*
FastLadder

**To Reproduce**
1. Turn on the hack
2. Go to the ladder
3. ????
4. PROFIT!!!

**Was the server lagging? - Was your ping high? - Were there any other factors different from normal gameplay?**
No no no

**Video of the event**
https://youtu.be/mi4OhtAFVPs

**Comment by thedarthonian** [comment]
Since it's not actually touching the ladder, the bypass has been patched by Fly#A
