### ISSUE TITLE
NoFall FalsePositive

### ISSUE THREAD

**Issue by KrUtOy228omg** [thedarthonian/KarmaAC#173]
**Minecraft Version & Client**
1.8.9 LiquidBounce

**Check [What check should trigger if bypass] [What check is triggered if bug]**
NoFall#4

**Description**
Its a bug

**To Reproduce**
1. Climb on ladder

**Was the server lagging? - Was your ping high? - Were there any other factors different from normal gameplay?**
No no no

**Video of the event**
https://youtu.be/PfZN9KbkDuY

**Comment by thedarthonian** [comment]
Added code to NoFall#4 that ensures it's aware of the block below it and acts accordingly.
