### ISSUE TITLE
Fly and FastLadder FalsePositive

### ISSUE THREAD

**Issue by KrUtOy228omg** [thedarthonian/KarmaAC#174]
**Minecraft Version & Client**
1.8.9

**Check [What check should trigger if bypass] [What check is triggered if bug]**
If a bug, which check is triggered (Fly#C, Speed#A etc).
Fly, FastLadder

**Description**
Trying to jump while inside of ladder

**To Reproduce**
1. Go to the ladder
2. Try to jump

**Was the server lagging? - Was your ping high? - Were there any other factors different from normal gameplay?**
No, no, I was jumping on the ladder

**Video of the event**
If applicable, please provide a video.
https://youtu.be/2ODZUWkaJ3Y

**Comment by thedarthonian** [comment]
The modified y change by touching the ladder was causing all sorts of havoc across both Fly and FastLadder checks, added code to detect legitimate jumps and act accordingly.
