### ISSUE TITLE
Many FalsePositives in lava

### ISSUE THREAD

**Issue by KrUtOy228omg** [thedarthonian/KarmaAC#175]
**Minecraft Version & Client**
1.8.9 LiquidBounce

**Check [What check should trigger if bypass] [What check is triggered if bug]**
Fly#C, Fly#A1, NoFall#5, NoFall#1, Fly#B2

**Description**
If a bug, a clear concise description of the behaviour that triggers the problem
Swiming in lava

**To Reproduce**
1. Go to lava
2. Try to jump out of it

**Was the server lagging? - Was your ping high? - Were there any other factors different from normal gameplay?**
No no no

**Video of the event**
https://youtu.be/aizwfUvTmz8

**Comment by thedarthonian** [comment]
Added onFire handling to NoFall and Fly#A & B, so far not been able to produce the issues again with the new code.
