### ISSUE TITLE
Lava + Breaking block under me = FalsePositive fly

### ISSUE THREAD

**Issue by KrUtOy228omg** [thedarthonian/KarmaAC#176]
**Minecraft Version & Client**
1.8.9  LiquidBounce

**Check [What check should trigger if bypass] [What check is triggered if bug]*
red FLY, Fly#B1, Fly#B2

**Description**
When on fire you trying to break block, it thinks this is fly

**To Reproduce**
1. Go to lava
2. Break block under yourself

**Was the server lagging? - Was your ping high? - Were there any other factors different from normal gameplay?**
no no, block was claimed

**Video of the event**
https://youtu.be/JEC6D2caaNw

**Comment by thedarthonian** [comment]
Ensured variables are kept limited while on/near the ground. Not been able to replicate this issue since the fix.
